# Alpaca API Keys — replace the values below with your actual keys
# Get your keys at: https://app.alpaca.markets → Paper Trading → API Keys

ALPACA_API_KEY    = "PKU4IWUKMXLN4Q7N2DBPH6DU27"
ALPACA_SECRET_KEY = "F3XqBu74Vycx2SooT2XVVMCda18CsTYWJHwUgVHMHepU"
